### ISSUE TITLE
There you are!

### ISSUE THREAD

**Issue by sniperrifle2004** [TASVideos/vba-rerecording#97]
Hi :),

I had been looking for the "official" fork of this for a while. I have been working on my own fork of vba-rerecording here: https://github.com/vba-rerecording/vba-rerecording

Now the question is: What do we do now? I have made quite a lot of changes already that I think will benefit the project, but you might want to look at them. At least I have fixed linux support and replaced autotools with cmake. I have also made a lot of issues for things I want to change, but some of those choices are opinionated (I really dislike having the two core versions controlled through build flags)

**Comment by vadosnaprimer** [comment]
aquanull has a github account. but he hasn't touched this emulator for years, so I think no one cares of it anymore. you could make a pull request, call aquanull to check it, and call adelikat for merging it if it's good. but it might be not worth it for an effectively dead emu. tasvideos has moved to other emulators for gbx/gba.

**Comment by sniperrifle2004** [comment]
Okay, then I guess I will continue working on it at that repository since that will be much easier. I think I will just change the name of the fork in the near future to avoid confusion (Which is the road of least resistance). Biz-Hawk looks like a better fit for TASVideos purposes, but there may be some interest in this project from other areas (For me at least as an interesting project to work on).

Thanks for your response!
