### ISSUE TITLE
Lua Scripts not loading

### ISSUE THREAD

**Issue by Shinygati** [TASVideos/vba-rerecording#99]
Tried multiple roms and supported Lua scripts and i just can't seem to get any Lua scripts loading i get no logs or anything when i browse for the file and hit run.. tried running as admin/compatibility mode and several older versions of vba-rerecording but i just cannot seem to get it to work.

I'm running windows 10 64-bit.

**Comment by Real96** [comment]
> Tried multiple roms and supported Lua scripts and i just can't seem to get any Lua scripts loading i get no logs or anything when i browse for the file and hit run.. tried running as admin/compatibility mode and several older versions of vba-rerecording but i just cannot seem to get it to work.
> 
> I'm running windows 10 64-bit.

you have to enable it.
`Options` -> `Head-up Display` -> `Text Display Options...`

**Comment by Legarad** [comment]
@Real96 it doesn't work for me, I have the same problem with my own rom dumped from my Pokemon Fire Red. and I try to load the Lua file, and it doesn't load.

**Comment by Real96** [comment]
> @Real96 it doesn't work for me, I have the same problem with my own rom dumped from my Pokemon Fire Red. and I try to load the Lua file, and it doesn't load.

Does the Lua window give you an error?

**Comment by Legarad** [comment]
@Real96 I already saw the problem, I had downloaded it in the wrong way.
